name: CI

on:
  push:
  release:
    types: [published]

jobs:
  athena:
    name: Build for Athena
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Setup Java"
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: "Build all"
        run: ./gradlew build

      - name: Spotless Check
        if: github.event_name != 'release'
        id: spotless
        run: |
          ./gradlew spotlessCheck

      - name: "Release: Get version number"
        id: get_version
        if: github.event_name == 'release'
        uses: battila7/get-version-action@v2

      - name: "Release: Get release info"
        id: get_release_info
        if: github.event_name == 'release'
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}

      # Add Maven Publishing
      - name: Publish to GitHub Packages
        if: github.event_name == 'release'
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.get_version.outputs.version-without-v }}

      - name: "Release: Upload vendordep"
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: Crewmate.json
          asset_name: Crewmate.json
          asset_content_type: application/json

      - name: Upload Release Assets
        if: github.event_name == 'release'
        run: |
          for file in build/repos/releases/crewmate/lib/Crewmate-java/${{ steps.get_version.outputs.version-without-v }}/*; do
            echo "Uploading $file"
            gh release upload ${{ github.event.release.tag_name }} "$file"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy Build Artifacts
        if: github.event_name == 'release'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          mkdir -p crewmate/lib/Crewmate-java/0.0.1/
          cp -r build/repos/releases/crewmate/lib/Crewmate-java/${{ steps.get_version.outputs.version-without-v }}/* crewmate/lib/Crewmate-java/0.0.1/
          git checkout --orphan pages
          git rm -rf .
          cp -r crewmate/lib/Crewmate-java/0.0.1/* .
          git add .
          git commit -m "Deploy build artifacts for version ${{ steps.get_version.outputs.version-without-v }}"
          git push origin pages -f
