name: "pre-release"

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  version-increment-spotless-check:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/spotless-check.yml
      - uses: ./.github/version-increment.yml

  release:
    needs: version-increment-spotless-check
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/release.yml
        with:
          new_version: ${{ needs.version-increment-spotless-check.outputs.new_version }}
      - run: git push
