name: "pre-release"

on:
  pull_request:
    branches:
      - "main"

jobs:
  version-increment-spotless-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/spotless-check.yml
      - uses: ./.github/workflows/version-increment.yml

  release:
    needs: version-increment-spotless-check
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/release.yml
        with:
          new_version: ${{ needs.version-increment-spotless-check.outputs.new_version }}
      - run: git push
