name: "pre-release"

on:
  pull_request:
    branches:
      - "main"

concurrency:
  group: "${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  spotless-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/spotless-check.yml@main

  version-increment:
    needs: spotless-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/version-increment.yml@main

  release:
    needs: version-increment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/release.yml@main
        with:
          new_version: ${{ needs.version-increment.outputs.new_version }}
