name: "pre-release"

on:
  pull_request:
    branches:
      - "main"

jobs:
  version-increment:
    uses: ./.github/workflows/version-increment.yml
  
  spotless-check:
    uses: ./.github/workflows/spotless-check.yml

  release:
    if: ${{ failure() }}
    needs: version-increment
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/release.yml
        with:
          new_version: ${{ needs.version-increment-spotless-check.outputs.new_version }}
      - run: git push
