on:
  workflow_call:
    inputs:
      new_version:
        type: string
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Publish gradle
        run: ./gradlew publish

      - name: Push changes
        uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build ${{ inputs.new_version }}"
          files: |
            LICENSE.txt
            build\repos\releases\crewmate\lib\Crewmate-java\${{ inputs.new_version }}\*.jar
            build\repos\releases\crewmate\lib\Crewmate-java\${{ inputs.new_version }}\*.pom
