name: Release

on:
  push:
  release:
    types: [published]

jobs:
  athena:
    name: Build for Athena
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
        
      - name: "Setup Java"
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          
      - name: "Build all"
        run: ./gradlew build
        
      - name: "Release: Get version number"
        id: get_version
        if: github.event_name == 'release'
        uses: battila7/get-version-action@v2
        
      - name: "Release: Get release info"
        id: get_release_info
        if: github.event_name == 'release'
        uses: bruceadams/get-release@v1.2.3
        env:
          GITHUB_TOKEN: ${{ github.token }}

      # Add Maven Publishing
      - name: Publish to GitHub Packages
        if: github.event_name == 'release'
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.get_version.outputs.version-without-v }}
          
      - name: "Release: Generate vendordep"
        if: github.event_name == 'release'
        run: ./gradlew generateVendorJson -Pversion=${{ steps.get_version.outputs.version-without-v }}
        
      - name: "Release: Upload vendordep"
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: build/vendordep/Crewmate.json
          asset_name: Crewmate.json
          asset_content_type: application/json
