on:
  workflow_call:

  push:
    branches-ignore:
      - main # Exclude pushes to the main branch
    paths-ignore:
      - ".*" # Exclude all directories starting with a "."
jobs:
  spotless-check:
    uses: ./.github/workflows/spotless-check.yml
  push:
    if: ${{ failure() }}
    needs: spotless-check
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
