on:
  push:
    branches-ignore:
      - main # Exclude pushes to the main branch
    paths-ignore:
      - ".*" # Exclude all directories starting with a "."
jobs:
  spotless-check:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/spotless-check.yml
      - run: git push