on:
  workflow_call:

  push:
    branches-ignore:
      - main # Exclude pushes to the main branch
    paths-ignore:
      - ".*" # Exclude all directories starting with a "."
jobs:
  spotless-check:
    uses: ./.github/workflows/spotless-check.yml
  push:
    runs-on: ubuntu-latest
    steps:
      - run: git push
