on:
  workflow_call:

jobs:
  spotless-check:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Spotless Check
        id: spotless
        run: |
          ./gradlew spotlessCheck
          echo "::set-output name=status::$?"

      - name: Spotless Apply
        if: steps.spotless.outputs.status != '0'
        run: |
          ./gradlew spotlessApply
          echo "Spotless check failed. Applied formatting changes."

      - name: Fail the Workflow
        if: steps.spotless.outputs.status != '0'
        run: exit 1