name: Test Job

on:
  workflow_call:

jobs:
  test-gradle:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Run tests with Gradle
        run: ./gradlew test
