name: Release
# TODO: rename main
on:
  push:
    branches: [ "Workflows" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  release:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}
        fetch-depth: 0

    - name: Debug
      run: |
        pwd
        ls

    - name: Find and increment version
      id: version
      run: |
        current_version=$(grep -oP "pubVersion = '\K\d+\.\d+\.\d+" publish.gradle)
        IFS='.' read -ra version_parts <<< "$current_version"
        ((version_parts[2]++))
        new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
        echo "New version: $new_version"
        echo "NEW_VERSION=$new_version" >> $GITHUB_ENV

    - name: Update version in publish.gradle
      run: sed -i "s/pubVersion = '.*'/pubVersion = '$NEW_VERSION'/" publish.gradle

    - name: Commit version increment
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add publish.gradle
        git commit -m "Increment version to ${{ env.NEW_VERSION }}"
    
    - name: Push changes
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.head_ref }}
        

    # Build your project and package the binaries here
    - name: Publish
      run: |
        ./gradlew publish

    - name: Create Release
      uses: release-drafter/release-drafter@v6
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: ${{ env.NEW_VERSION }}
        name: ${{ env.NEW_VERSION }}
        publish: true
        prerelease: true

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: |
            build\repos\releases\crewmate\lib\Crewmate-java\${{ env.NEW_VERSION }}\*.jar
            build\repos\releases\crewmate\lib\Crewmate-java\${{ env.NEW_VERSION }}\*.pom

