name: Release

on:
  release:
    types: [created]

jobs:

  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get next version
      uses: reecetech/version-increment@2024.4.3
      id: version
      with:
        scheme: semver
        increment: minor

    # Build your project and package the binaries here
    - name: Build
      run: |
        ./gradlew build
        ./gradlew publish

    - name: Create Release
      uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag: ${{ steps.version.outputs.version }}
        name: ${{ steps.version.outputs.version }}
        publish: true
        prerelease: true

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: |
            build\repos\releases\crewmate\lib\Crewmate-java\0.0.1\*.jar
            build\repos\releases\crewmate\lib\Crewmate-java\0.0.1\*.pom

