name: Version Increment

on:
  workflow_call:
    outputs:
      new_version:
        description: "The incremented version number"
        value: ${{ jobs.version-increment.outputs.new_version }}

jobs:
  version-increment:
    runs-on: ubuntu-latest

    outputs:
      new_version: ${{ steps.version.outputs.new_version }}

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
      - name: Find and increment version
        id: version
        run: |
          current_version=$(grep -oP "pubVersion = '\K\d+\.\d+\.\d+" publish.gradle)
          IFS='.' read -ra version_parts <<< "$current_version"
          ((version_parts[2] = 0))
          ((version_parts[1]++))
          new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT

      - name: Update version in publish.gradle
        run: sed -i "s/pubVersion = '.*'/pubVersion = '${{ steps.version.outputs.new_version }}'/" publish.gradle
      - run: |
          pwd
          ls -la
          git init
      - uses: EndBug/add-and-commit@v9
        with:
          add: "src"
          default_author: github_actor
          fetch: true
          message: "Update crewmate version to ${{ steps.version.outputs.new_version }}"
          push: true
